<div class="row">
<link href="{{ base_url }}asset/lib/css/emoji.css" rel="stylesheet">
<!-- start emoji!-->
	<script src="{{ base_url }}asset/lib/js/config.js"></script>
    <script src="{{ base_url }}asset/lib/js/util.js"></script>
    <script src="{{ base_url }}asset/lib/js/jquery.emojiarea.js"></script>
    <script src="{{ base_url }}asset/lib/js/emoji-picker.js"></script>
	
<!-- start emoji!-->
                   <!-- Start Slider -->
<div id="sliderWrapp">
    <!-- Start cssSlider.com -->
    <!-- Generated by cssSlider.com 2.1 -->
    <link rel="stylesheet" href="{{ base_url }}bootstrap/cssslider_files/csss_engine1/style.css">
	<script src='https://cdnjs.cloudflare.com/ajax/libs/autosize.js/3.0.15/autosize.min.js'></script>
    <!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
    <!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
     <div class='csslider1 autoplay' style="width:100%">
    <input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
    <input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
    <input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
    <input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
    <input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
    <input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
    <input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
    <ul>
      <li class="cs_skeleton" style="height:300px;"><img src="{{ base_url }}bootstrap/cssslider_files/csss_images1/2017yamahayzfr6thunderhilljensenbeeler06.jpg" style="width: 100%;"></li>

      <li class='num0 img slide'> <img class="img_slide0" src='{{ base_url }}asset/default_news.png' alt='img1' title='img1' /></li>
      <li class='num1 img slide'> <img class="img_slide1" src='{{ base_url }}bootstrap/cssslider_files/csss_images1/img2.jpg' alt='img2' title='img2' /></li>
      <li class='num2 img slide'> <img class="img_slide2" src='{{ base_url }}bootstrap/cssslider_files/csss_images1/img3.jpg' alt='img3' title='img3' /></li>
    </ul><div class="cs_engine"><a href="http://cssslider.com">css slider</a> by cssSlider.com v2.1</div>
    <div class='cs_description'>
      <label class='num0 b_func'><span class="cs_title"><span id="post0" class="cs_wrapper col_white"> </span><div id="detailpost0" class="detpost"></div></span></label>
      <label class='num1 b_func'><span class="cs_title"><span id="post1" class="cs_wrapper col_white"> </span><div id="detailpost1" class="detpost"></div></span></label>
      <label class='num2 b_func'><span class="cs_title"><span id="post2" class="cs_wrapper col_white"> </span><div id="detailpost2" class="detpost"></div></span></label>
    </div>
    <div class='cs_play_pause'>
      <label class='cs_play b_func' for='cs_play1'><span><i></i><b></b></span></label>
      <label class='cs_pause num0 b_func' for='cs_pause1_0'><span><i></i><b></b></span></label>
      <label class='cs_pause num1 b_func' for='cs_pause1_1'><span><i></i><b></b></span></label>
      <label class='cs_pause num2 b_func' for='cs_pause1_2'><span><i></i><b></b></span></label>
      </div>
    <div class='cs_arrowprev'>
      <label class='num0 b_func' for='cs_slide1_0'><span><i></i><b></b></span></label>
      <label class='num1 b_func' for='cs_slide1_1'><span><i></i><b></b></span></label>
      <label class='num2 b_func' for='cs_slide1_2'><span><i></i><b></b></span></label>
    </div>
    <div class='cs_arrownext'>
      <label class='num0 b_func' for='cs_slide1_0'><span><i></i><b></b></span></label>
      <label class='num1 b_func' for='cs_slide1_1'><span><i></i><b></b></span></label>
      <label class='num2 b_func' for='cs_slide1_2'><span><i></i><b></b></span></label>
    </div>
    <div class='cs_bullets'>
      <label class='num0' for='cs_slide1_0'> <span class='cs_point'></span>
        <span class='cs_thumb'><img class="img_slide0" src='{{ base_url }}bootstrap/cssslider_files/csss_tooltips1/img1.jpg' alt='img1' title='img1' style="width: 50px; height: 30px" /></span></label>
      <label class='num1' for='cs_slide1_1'> <span class='cs_point'></span>
        <span class='cs_thumb'><img class="img_slide1" src='{{ base_url }}bootstrap/cssslider_files/csss_tooltips1/img2.jpg' alt='img2' title='img2' style="width: 50px; height: 30px"/></span></label>
      <label class='num2' for='cs_slide1_2'> <span class='cs_point'></span>
        <span class='cs_thumb'><img class="img_slide2" src='{{ base_url }}bootstrap/cssslider_files/csss_tooltips1/img3.jpg' alt='img3' title='img3' style="width: 50px; height: 30px"/></span></label>
    </div>
    </div>
    <!-- End cssSlider.com -->

<script type="text/javascript">
	$(function(){
		$.post("cont_slide", function(data) {
			var obj = JSON.parse(data);
			for (var k in obj){
				$("#post"+k).html("<a onclick='window.location.replace(\"view_post?eid_post="+obj[k]['id_post']+"\")' class='judul_post'>"+obj[k]['post_title']+"</a>");
				$("#detailpost"+k).html(obj[k]['full_name']+" - "+formatDate2(new Date(obj[k]['post_date'])));
				$('.img_slide'+k).attr('src', '{{ base_url }}asset/'+obj[k]['media']);
			}
			// document.getElementById('post2').innerHTML = 
				// "author : " + obj[1]['username'] + "<br/>" +
				// "title : " + obj[1]['post_title'];
				// $('.img_slide1').attr('src', '{{ base_url }}asset/'+obj[1]['media']);
				
			// document.getElementById('post3').innerHTML = 
				// "author : " + obj[2]['username'] + "<br/>" +
				// "title : " + obj[2]['post_title'];
				// $('.img_slide2').attr('src', '{{ base_url }}asset/'+obj[2]['media']);

		});
	});
	function formatDate2(date) {
		return date.getDate()+'/'+date.getMonth()+'/'+date.getFullYear()+' '+date.getHours()+':'+date.getMinutes();
	}
</script>

</div>
<!-- End Slider -->

<!-- taxonomi dashboard !-->
	<div class="col-md-12">
		<div class="x_panel">	
			<div class="col-md-9 col-sm-9 col-xs12">
				<h4>Recent Activity</h4>
					<ul id="body_post" class="messages"></ul>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<div class="x_title">
					<h4>Top Taxonomi Performance</h4>
					<div class="clearfix"></div>
				</div>
				<div id="tag_div" class="col-md-12 col-sm-12 col-xs-6">

				</div>
			</div>
		</div>
	</div>
</div>
<!-- end of taxonomi dashboard !-->

<!-- modal del comment !-->
<div id="modal_del_com" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
				</button>
				<h4 class="modal-title" id="myModalLabel2">Delete Comment</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure to delete this comment.?</p>
				<span id = "id_comment" hidden></span>
				<span id = "id_post" hidden></span>
				<span id = "c_comment" hidden></span>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button onclick="proses_del_comment()" type="button" class="btn btn-danger">Delete</button>
			</div>

		</div>
	</div>
</div>
<!-- end modal !-->
	
	<!-- start emoji !-->
	<script>
      //$(function() {
        // // Initializes and creates emoji set from sprite sheet
        // window.emojiPicker = new EmojiPicker({
          // emojiable_selector: '[data-emojiable=true]',
          // assetsPath: '{{ base_url }}asset/lib/img/',
          // popupButtonClasses: 'fa fa-smile-o'
        // });
        // // Finds all elements with `emojiable_selector` and converts them to rich emoji input fields
        // // You may want to delay this step if you have dynamically created input fields that appear later in the loading process
        // // It can be called as many times as necessary; previously converted input fields will not be converted again
        // window.emojiPicker.discover();
      // });
    </script>
    <script>
      //// Google Analytics
      // (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      // (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      // m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      // })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      // ga('create', 'UA-49610253-3', 'auto');
      // ga('send', 'pageview');
    </script>
<!-- end emoji !-->
<script type="text/javascript">
	autosize(document.querySelectorAll('textarea'));
	$.ajax({
		url     : 'get_post',
		type    : "POST",
		success : function(data) {
			new Date($.now());
			var obj = JSON.parse(data);
			for (var k in obj){
				var id_post = obj[k]['id_post'];
				var dt = obj[k]['post_date'];
				var ul = document.createElement('li');
				ul.innerHTML = "<img src='{{ base_url }}asset/image_post/"+obj[k]['media']+"' class='avatar' alt='Avatar' style='height:150px; width:150px; margin-right:10px'>"+
									"<div class='message_date'>"+
										obj[k]['full_name']+
										"<br>"+
										formatDate(new Date(dt), new Date(), 'comment')+
									"</div>"+
									"<div class='message_wrapper' style='margin:0px'>"+
										"<blockquote class='message' style='color:black; height:100px'><a onclick='window.location.replace(\"view_post?eid_post="+obj[k]['id_post']+"\")' class='judul_post'>"+obj[k]['post_title']+"</a></blockquote>"+
										"<img src='{{ base_url }}asset/like.png' width='20px'>"+
										"<span id='jumlah_like"+obj[k]['id_post']+"'>"+obj[k]['jumlah_like']+
										"</span>"+
										"<div>"+
											"<div id='b_like"+obj[k]['id_post']+"' class='b_like' style='float:left; width:12%;'>"+
												"<a onclick='like_post(\""+obj[k]['b_like']+"\", "+obj[k]['id_post']+", \""+obj[k]['user_unlike']+"\")' style='cursor:pointer;'><h4><i class='fa "+obj[k]['b_like']+"'> Like </i></h4></a>"+
											"</div>"+
											"<div class='accordion' id='accordion' role='tablist' aria-multiselectable='true'>"+
												"<div class='panel' style='background:#fff; border-color:#fff; margin:0'>"+
													"<a class='panel-heading collapsed' onclick='view_comment("+obj[k]['id_post']+","+obj[k]['c_comment']+", 0)' role='tab' id='headingThree' data-toggle='collapse' data-parent='#accordion' href='#collapseThree"+obj[k]['id_post']+"' aria-expanded='false' aria-controls='collapseThree' style='background:#fff; padding:0; border:0;'>"+
														"<h4><i class='fa fa-comments-o'> Comment (<span id='count_comment"+obj[k]['id_post']+"'>"+obj[k]['c_comment']+"</span>)</i></h4>"+
													"</a>"+
													"<div id='collapseThree" + obj[k]['id_post'] + "' class='panel-collapse collapse' role='tabpanel' aria-labelledby='headingThree' style='background:#f2f5f7'>"+
														"<div id='lists_comment"+obj[k]['id_post']+"' class='panel-body'>"+
														"</div>"+
														"<div class='panel-body'>"+
															"<div  class='comend_div' id='comment_div"+obj[k]['id_post']+"' contentEditable='true' data-text='Type Comment...' style='word-break: break-all; border: solid 1px #ccc; border-radius: 10px; display:inline-block; min-height: 30px; width: 90%; padding:5px; background:#ffffff';>"+
															"</div> &nbsp"+
															"<img id='button_send' onclick='send_comment("+obj[k]['id_post']+","+obj[k]['c_comment']+")' src='{{ base_url }}asset/send_biru.png' width='30px' style='cursor: pointer;'>"+
														"</div>"+
													"</div>"+
												"</div>"+
											"</div>"+
										"</div>"+
									"</div>";
				document.getElementById('body_post').appendChild(ul);
				if(obj[k]['fn_media']){
					//alert(obj[k]['id_post']+' -> ada');
					var sk = obj[k]['fn_media'].split("____");
					var media = '';
					console.log(obj[k]['id_post']);
					for (var k in sk){
						var skk = sk[k].split("----");
						media = media+"<span class='fs1 text-info' aria-hidden='true' data-icon=''></span>"+
									"<a href = '{{ base_url }}public/downFiles?eid_upload="+skk[1]+"' style='cursor:pointer'><i class='fa fa-paperclip'></i> "+skk[0]+" </a><br>";
					}
					//console.log(media);
					//$("#media_post"+id_post).html(media);
				}
			}
		}
	});
	
	//taxonomi
	$.ajax({
		url     : 'get_taxanomi_das',
		type    : "POST",
		success : function(data) {
			var obj = JSON.parse(data);
			for(var k in obj) {
				var tag = (obj[k]['c_taxonomi']/obj[k]['count_wp'])*100;
				var div = document.createElement('DIV');
				div.innerHTML ="<p>"+obj[k]['taxonomi']+"</p>"+
								"<div class=''>"+
									"<div style='width:76%'>"+
										"<div style='margin-left:"+(tag-4)+"%;'>"+
											"<span style='color: #fff; font-size:10px; line-height:1.333; text-shadow:none; padding:1px 5px; background: #1ABB9C; border-radius:4px;'>"+(tag.toFixed())+"%"+
											"</span>"+
										"</div>"+
										"<span style='display: block;bottom: -6px;left: 50%;width: 0;height: 0;margin-left: "+tag+"%;overflow: hidden;border: 3px solid transparent;border-top-color: #1ABB9C;'>"+
										"</span>"+
									"</div>"+
									"<div class='progress progress_sm' style='width: 76%;'>"+
										"<div id='div_das_tags' class='progress-bar bg-green' role='progressbar' data-transitiongoal='"+tag+"' style='width: "+tag+"%'></div>"+
									"</div>"+
								"</div>";
				document.getElementById('tag_div').appendChild(div);
			}
		}
	});
	
	
	function like_post(logo, id_post, user_unlike){
		var func = '';
		if(logo == 'fa-thumbs-o-up'){
			func = 'unlike';
		}else{
			func = 'like';
		}
		$.ajax({
			url		: 'button_like',
			data	: {eid_post: id_post, euser_unlike: user_unlike, efunc: func},
			type	: 'POST',
			success	: function(data){
				var obj = JSON.parse(data);
				$("#jumlah_like"+id_post).html(obj[0]['jumlah_like']);
				$("#b_like"+id_post).html("<a onclick='like_post(\""+obj[0]['b_like']+"\", "+id_post+", \""+obj[0]['user_unlike']+"\")' style='cursor:pointer;'><h4><i class='fa "+obj[0]['b_like']+
				"'> Like </i></h4></a>");
			}
		});
	}
	
	function view_comment(id_post, c_comment, view){
		new Date($.now());
		var data;
		$.ajax({
			url:'views_comment',
			data:{ eid_post : id_post },
			type:'POST',
			success:function(data){

				$("#lists_comment"+id_post).empty();
				var action = '';
				var count = 0;
				var divv = document.createElement('DIV');
				var obj = JSON.parse(data);
				if(c_comment>5 && view == 0){
					divv.innerHTML = "<a onclick='view_comment("+id_post+","+c_comment+",1)' style='cursor: pointer;'>View All</a>";
					var count = c_comment - 1;
				}else{
					if(c_comment>5){
						divv.innerHTML = "<a onclick='view_comment("+id_post+","+c_comment+",0)' style='cursor: pointer;'>View Simple</a>";
					}
					count = 4;
				}
				document.getElementById('lists_comment'+id_post).appendChild(divv);
				for(var k in obj.isi) {
					if(count<5){
						var s_com = obj.isi[k]['comment_content'].split(" ");
						if(s_com.length > 15){
							
						}
						var dt = obj.isi[k]['post_date'];
						var div = document.createElement('DIV');
						var div2 = document.createElement('DIV');
						div.setAttribute("class", "col-md-12  div_comment");
						div.innerHTML =	"<div class='x_content'>"+
											"<ul class='list-unstyled' style='padding:-100px'>"+
												"<li>"+
													"<a>"+
														"<span class='image'>"+
															"<img class='img-circle' src='{{ base_url }}asset/photo_user/"+obj.isi[k]['photo']+"' alt='img' style='width:35px'/> &nbsp"+
														"</span>"+
														"<span>"+
															"<span style='font-weight: bold;'>"+obj.isi[k]['username']+"</span> &nbsp"+
															"<span id='span_com_"+id_post+"_"+k+"' class='message' style='word-wrap: break-word; color:black;'>"+obj.isi[k]['comment_content']+"</span>"+
														"</span>"+
														"<br>"+
														"<span class='time' style='position: relative; left: 0%;'>"+formatDate(new Date(dt), new Date(), 'comment')+action+" </span>"+
													"</a>"+
												"</li>"+
											"</ul>"+
										"</div>"+
										
										"<div id='div_dropdown"+obj.isi[k]['id_comment']+"' class='btn-group'  style='position:absolute; left: 95%;'>"+
											"<span data-toggle='dropdown' class='caret' style='cursor:pointer; width:10px;'></span>"+
											"<ul role='menu' class='dropdown-menu' style='min-width: 10px'>"+
												"<li>"+
													"<a onclick='delete_comment("+obj.isi[k]['id_comment']+","+id_post+","+c_comment+")'><i class='fa fa-trash-o'> Delete</i></a>"+
												"</li>"+
											"</ul>"+
										"</div>";
						document.getElementById('lists_comment'+id_post).appendChild(div);
						if(obj.isi[k]['id_user']!=obj['id_user']){
							$("#div_dropdown"+obj.isi[k]['id_comment']).addClass('hidden');
						}
					}
					count--;
				}
			}
		});
    }
	function delete_comment(id_comment, id_post, c_comment){
		$('#id_post').val(id_post);
		$('#id_comment').val(id_comment);
		$('#c_comment').val(c_comment);
		$("#modal_del_com").modal('show');
	}
	
	function proses_del_comment(){
		var id_post = $('#id_post').val();
		var id_comment = $('#id_comment').val();
		var c_comment = $('#c_comment').val();
		$("#modal_del_com").modal('hide');
		$.ajax({
			url : 'delete_comment',
			data:{eid_comment: id_comment, eid_post: id_post},
			type: 'POST',
			success:function(data){
				new PNotify({
					title: 'Delete Success',
					text: 'Comment has been deleted.!',
					type: 'success',
					styling: 'bootstrap3'
				});
				view_comment(id_post, c_comment, 0);
				count_comment(id_post);
			}
		});
	}
	
	function count_comment(id_post){
		var data;
		$.ajax({
			url:'count_comment',
			data:{eid_post : id_post},
			type: 'POST',
			success:function(data){
				var obj = JSON.parse(data);
				document.getElementById("count_comment"+id_post).innerHTML = obj[0]['c_comment'];
			}
		});
	}
	
	function send_comment(id_post, c_comment){
		var comment = document.getElementById('comment_div'+id_post).innerHTML;;
		$.ajax({
			url:'post_comment',
			data:{eid_post : id_post, ecomment : comment},
			type: 'POST',
			success:function(data){
				view_comment(id_post, c_comment, 0);
				count_comment(id_post);
				$( ".comend_div" ).empty();
			}
		});
	}
	
	function formatDate(date, date2, views) {
		var monthNames = [
			"January", "February", "March",
			"April", "May", "June", "July",
			"August", "September", "October",
			"November", "December"
		];

		var day 		= date.getDate();
		var monthIndex 	= date.getMonth();
		var year 		= date.getFullYear();
		var jam 		= date.getHours();
		var menit 		= date.getMinutes();
		var second 		= date.getSeconds();
		
		var day2		= date2.getDate();
		var monthIndex2	= date2.getMonth();
		var year2		= date2.getFullYear();
		var jam2		= date2.getHours();
		var menit2		= date2.getMinutes();
		var second2		= date2.getSeconds();
		
		var rt = '';
		if(year == year2){
			if(monthIndex == monthIndex2 && day == day2){
				if(jam == jam2){
					if(menit == menit2){
						//rt = second2 - second+' Secn';
						if(views == 'comment'){
							rt = 'Recently';
						}else if(views == 'post'){
							rt = '<strong>Recently</strong>';
						}
					}else{
						f_menit = menit2 - menit;
						if(views == 'comment'){
							rt = menit2 - menit+' Mins';
						}else if(views == 'post'){
							rt = "<strong>"+f_menit+" Mins </strong>";
						}
					}
				}else{
					f_jam = jam2 - jam;
					if(views == 'comment'){
						rt = jam2 - jam+' Hours';
					}else if(views == 'post'){
						rt = "<strong>"+f_jam+" Hours </strong>";
					}
				}
			}else{
				if(views == 'comment'){
					rt = day + ' ' + monthNames[monthIndex] + ' '+ jam+':'+menit;
				}else if(views == 'post'){
					rt = "<h3 class='date text-info'>"+day +"</h3><p class='month'>"+ monthNames[monthIndex]+ "</p>";
				}
			}
		}else{
			if(views == 'comment'){
				rt = day + ' ' + monthNames[monthIndex] + ' ' + year +' '+ jam+':'+menit;
			}else if(views == 'post'){
				rt =  "<h3 class='date text-info'>"+day +"</h3><p class='month'>"+ monthNames[monthIndex]+" "+ year +"</p>";
			}
		}
		return rt;
	}
</script>

<!-- Start CSS Slider -->
<style>

</style>
<!-- End CSS Slider -->